---
- name: "Ansible 101"
  hosts: switches
  gather_facts: no
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: dajo
    ansible_password: cisco
    ansible_become_password: cisco

  tasks:
    - name: Show Version
      cisco.ios.ios_command:
        commands: show version
      register: output

    - name: Print output
      debug:
        msg: "{{ output.stdout_lines }}"
