- name: "Configure switch_01"
  hosts: switch_01  # Target only switch_01
  gather_facts: yes  # Gather facts before running tasks (optional)

  tasks:
    - name: Show interface status
      cisco.ios.ios_command:
        commands: show ip interface brief
      register: interface_status

    - name: Print interface status
      debug:
        msg: "{{ interface_status.stdout_lines }}"
